#https://www.baeldung.com/liquibase-refactor-schema-of-java-app
#mvn liquibase:generateChangeLog
#mvn liquibase:diff
changeLogFile=src/main/resources/liquibase-changeLog.xml
url=jdbc:postgresql://santa_crm_db:5432/santa_db_anvoice
username=santa_crm
password=SantaCRM.396
driver=org.postgresql.Driver
referenceUrl=hibernate:spring:bg.latona.santa?dialect=org.hibernate.dialect.PostgreSQLDialect&hibernate.physical_naming_strategy=org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy&hibernate.implicit_naming_strategy=org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
diffChangeLogFile=src/main/resources/liquibase-diff-changeLog.xml
verbose=false